### ISSUE TITLE
notification of title or aliar not working.

### ISSUE THREAD

**Issue by jcarreja** [nagy135/subtube#2]
Notification of title or alias is not working for me in sxiv.

**Comment by nagy135** [comment]
Ye i originally wrote this a long time ago and few months ago I rewrote it from scratch because it was spaghetti ...i didnt update README tho so that feature isnt there anymore. But I will put it back there since its very simple ...today or tomorrow :) If you have anything else feel free to open issue

**Comment by nagy135** [comment]
Ok so i added options `subtube name` and `subtube name_length` since it takes some ms to fetch both of those so the first one is 2x faster but doesnt show time ....updated README to reflect my current sxiv key-handler
