### ISSUE TITLE
subtube name slow

### ISSUE THREAD

**Issue by Randalix** [nagy135/subtube#7]
Wouldn't it be much faster to save the title along with the thumbnail. It could be simply in the title. We would be able to just read the title in the sxiv bar then. Or save the title as metadata. subtube name could then fetch the name from there.

**Comment by nagy135** [comment]
This approach is mostly relic from my initial version that was like 20 lines of bash.
First free evening i ll find I will surely make update since the whole resources structure is kinda wrong, at least it should be in XDG_CONFIG_HOME, it should not relly on Makefile (issues with AUR updates) and should be probably separated in more files to avoid using regexes where not needed (i have some edge cases there from time to time).

But to reply to "title in sxiv bar" I dont think i like that. I personally abuse sxiv's key handler and use it to open video in other programs, copy url to clipboard etc and it would lead to another matching. Its fine as notification, but it should be instant! No need to refetch those when they can be stored during update and thats a good point. Will keep you posted

**Comment by nagy135** [comment]
now it stores **video length** and **title** on update and just shows it everywhere else (with fallback to download if not present).  If it doesnt work for you, I ll reopen issue
